# Generated by Django 5.2.3 on 2025-07-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, default='Peter', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, default='Okon', max_length=30),
            preserve_default=False,
        ),
    ]
